### ISSUE TITLE
Error in the doc of ser targets

### ISSUE THREAD

**Issue by ypiguet-epfl** [aseba-community/dashel#24]
File [dashel/dashel.h](https://github.com/aseba-community/dashel/blob/f3a540ed113af5a2a3cfded0ffc7cfda6936c084/dashel/dashel.h) states that _either port or device must be given_. It should be _either port, name (on supported platforms), or device must be given_.

**Comment by stephanemagnenat** [comment]
Fixed by commit 960e19b5dfba27d139796133307586520ab377df.
