### ISSUE TITLE
Compilation warning on mingw491_32

### ISSUE THREAD

**Issue by omichel** [aseba-community/dashel#8]
```
$ make
d:/msys/home/michel/develop/webots-master/projects/robots/thymio/libraries/dashel-src/dashel/dashel-win32.cpp:58:0: warning: "_WIN32_WINNT" redefined [enabled by default]
 #define _WIN32_WINNT 0x0501
 ^
In file included from d:/msys/home/michel/develop/webots-master/mingw/i686-w64-mingw32/include/crtdefs.h:10:0,
                 from d:/msys/home/michel/develop/webots-master/mingw/i686-w64-mingw32/include/wchar.h:9,
                 from d:/msys/home/michel/develop/webots-master/mingw/i686-w64-mingw32/include/c++/cwchar:44,
                 from d:/msys/home/michel/develop/webots-master/mingw/i686-w64-mingw32/include/c++/bits/postypes.h:40,
                 from d:/msys/home/michel/develop/webots-master/mingw/i686-w64-mingw32/include/c++/bits/char_traits.h:40,
                 from d:/msys/home/michel/develop/webots-master/mingw/i686-w64-mingw32/include/c++/string:40,
                 from d:/msys/home/michel/develop/webots-master/projects/robots/thymio/libraries/dashel-src/dashel/dashel.h:44,
                 from d:/msys/home/michel/develop/webots-master/projects/robots/thymio/libraries/dashel-src/dashel/dashel-win32.cpp:41:
d:/msys/home/michel/develop/webots-master/mingw/i686-w64-mingw32/include/_mingw.h:229:0: note: this is the location of the previous definition
 #define _WIN32_WINNT 0x502
 ^
```
Can be fixed by the following patch:
```
diff --git a/dashel/dashel-win32.cpp b/dashel/dashel-win32.cpp
index b55c2a4..c0df90a 100644
--- a/dashel/dashel-win32.cpp
+++ b/dashel/dashel-win32.cpp
@@ -55,6 +55,9 @@
        #pragma comment(lib, "comsuppw.lib")
 #endif // _MSC_VER

+#ifdef _WIN32_WINNT
+#undef _WIN32_WINNT
+#endif
 #define _WIN32_WINNT 0x0501
 #include <winsock2.h>
 #include <windows.h>
```
However, I am unable to create a branch on this repository to submit this patch for review. Can you help me?

**Comment by stephanemagnenat** [comment]
I have made a fix for `_WIN32_WINNT` in commit 896de1f. Rather than undefining it, I check if it is already defined, and if not, I define it. This seems cleaner then redefining it. Please check if Dashel compiles with this change, and if so, please close this issue.

**Comment by omichel** [comment]
Yes, your patch fixes the warning but it also changes the behavior: on my system `_WIN32_WINNT` will defined to 0x0502 with your patch, whereas with my patch it was defined to 0x0501 as with the original version. But maybe, that's no problem? I will test it right now and confirm.

**Comment by stephanemagnenat** [comment]
Indeed it changes the behaviour, but it is on purpose. I do not know what the `_WIN32_WINNT` define is supposed to do, but if it is defined, it seems a bad idea for me to have our code changing it.

**Comment by omichel** [comment]
Yes, I agree with you. I suspected it could be used to force the use of a specific version for the following Windows system include, but if it's not the case, then, it's better to keep the actual value as your patch does. I could recompile everything nicely with your patch without any warning. The resulting binaries seems to work as well.
